[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "wipe"]
set = true

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = '~/scripts/kitty_reload.sh'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.vesktop]
input_path = './templates/discord.css'
output_path = '~/.config/vesktop/themes/matugen.css'

[templates.gtk3]
input_path = './templates/gtk_colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk_colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
